version: "3.9"
   
services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  mongo:
    image: mongo
    ports:
      - "27107:27017"
    volumes:
      - ./test_data:/mnt/test_data
  
  reportree:
    build: reportree
    tty: true
    volumes:
      - ./rt_runs:/mnt/rt_runs
    ports:
      - "7000:7000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./rt_runs:/rt_runs
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
      - mongo
      - reportree

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    # volumes:
    #   - static:/app/static
    depends_on:
      - django
  
  react:
    build: ./dashboard
    command: npm start
    ports:
      - 3000:3000
    # env_file:
    #   - ./.env.dev
    tty: true
    # environment:
    #   - SOME_ENVVAR=true
    volumes:
       - ./dashboard/src:/app/src:ro  # Must be inside Dockerfile WORKDIR