version: "3.9"
   
services:
  postgres-init:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    entrypoint: ["sh", "-c", "chown -R 1000:1000 /var/lib/postgresql/data"]
  
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    user: "1000"
    depends_on:
      postgres-init:
        condition: service_completed_successfully

  mongo:
    image: mongo # Computerome runs 4.2.8
    ports:
      - "27107:27017"
    volumes:
      - ./data/mongo:/data/db
      - ./dumps/mongo:/dumps
      - ./scripts/mongosh:/scripts
  
  bio_api:
    build: ./bio_api
    tty: true
    volumes:
      - ./tmp:/tmp
      - ./bio_api:/app
    ports:
      - "8001:8001"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./rt_runs:/rt_runs
      - ./test_data:/mnt/test_data
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
      - mongo
      - bio_api

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #     - 8080:80
  #   # volumes:
  #   #   - static:/app/static
  #   depends_on:
  #     - django
  
  # react:
  #   build: ./dashboard
  #   command: npm start
  #   ports:
  #     - 3000:3000
  #   # env_file:
  #   #   - ./.env.dev
  #   tty: true
  #   # environment:
  #   #   - SOME_ENVVAR=true
  #   volumes:
  #      - ./dashboard/src:/app/src:ro  # Must be inside Dockerfile WORKDIR
