# Generated by Django 4.2.1 on 2023-05-09 14:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sequences', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comparisons.species')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None)),
                ('field_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NEW', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.CharField(blank=True, max_length=80, null=True)),
                ('folder_path', models.FilePathField(blank=True, null=True)),
                ('newick', models.TextField(blank=True, null=True)),
                ('analysis_type', models.CharField(choices=[('cgmlst', 'cgMLST'), ('SNP', 'SNP')], max_length=6)),
                ('analysis_subtype', models.CharField(blank=True, max_length=10, null=True)),
                ('analysis_params', models.JSONField(blank=True, default=dict)),
                ('microreact_project', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sequence_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comparisons.sequenceset')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
