# Generated by Django 4.2.1 on 2023-05-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_cluster_potentialoutbreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cgmlst', 'cgMLST'), ('snp', 'SNP')], max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='analysis_type',
        ),
        migrations.AddConstraint(
            model_name='analysistool',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='tool_name_version_unique'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comparisons.analysistool'),
        ),
    ]
