# Generated by Django 4.1.9 on 2023-07-17 11:22

import bio_api.classes
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_tree_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='data_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=bio_api.classes.TBRMetadata.get_field_list, size=None),
        ),
    ]
