# Generated by Django 4.1.9 on 2023-07-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0003_alter_comparison_data_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='data_fields',
            new_name='tbr_data_fields',
        ),
        migrations.RenameField(
            model_name='comparison',
            old_name='field_data',
            new_name='tbr_field_data',
        ),
    ]
