# Generated by Django 4.1.2 on 2023-05-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0004_basetool_rename_analysis_params_comparison_params_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
    ]
