# Generated by Django 4.1.9 on 2023-07-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0005_comparison_lims_data_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='lims_field_data',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='tbr_field_data',
        ),
    ]
