# Generated by Django 4.1.2 on 2023-05-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0005_alter_species_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
