# Generated by Django 4.1.9 on 2023-07-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0006_remove_comparison_lims_field_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='microreact_project',
        ),
    ]
