# Generated by Django 4.1.9 on 2023-07-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0007_remove_comparison_microreact_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='dm_status',
            field=models.CharField(choices=[('NODATA', 'No data'), ('PENDING', 'Pending'), ('VALID', 'Valid'), ('ERROR', 'Request was unsuccesful')], default='NODATA', max_length=15),
        ),
    ]
