# Generated by Django 4.1.2 on 2023-05-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0007_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='sequence_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comparisons.sequenceset'),
            preserve_default=False,
        ),
    ]
