# Generated by Django 4.1.9 on 2023-07-18 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0008_alter_comparison_dm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='id',
        ),
        migrations.AddField(
            model_name='tree',
            name='dashboard_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tree',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
