# Generated by Django 4.1.9 on 2023-07-19 08:53

import bio_api.classes
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comparisons', '0010_alter_comparison_dm_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tbr_data_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=bio_api.classes.TBRMetadata.get_field_list, size=None)),
                ('lims_data_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=bio_api.classes.LIMSMetadata.get_field_list, size=None)),
                ('dashboard_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comparisons.tree')),
            ],
        ),
    ]
