# Generated by Django 4.1.2 on 2023-05-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0010_remove_comparison_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='base_tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comparisons.basetool'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='elapsed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='error_msg',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='comparison',
            name='folder_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='linkage_method',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('COMPLETE', 'Complete'), ('UPGMA', 'UPGMA'), ('NJ', 'Neighbor Joining')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='comparison',
            name='microreact_project',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='newick',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='comparison',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NEW', max_length=15),
        ),
    ]
