# Generated by Django 4.1.2 on 2023-05-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0011_comparison_base_tool_comparison_elapsed_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='base_tool',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='error_msg',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='field_data',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='folder_path',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='linkage_method',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='microreact_project',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='newick',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='params',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='status',
        ),
    ]
