# Generated by Django 4.1.9 on 2023-07-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0011_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='lims_data_fields',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='tbr_data_fields',
        ),
    ]
