# Generated by Django 4.1.9 on 2023-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0012_remove_comparison_lims_data_fields_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparison',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='potentialoutbreak',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['-created_at']},
        ),
    ]
