# Generated by Django 4.1.2 on 2023-05-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0012_remove_comparison_base_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
