# Generated by Django 4.1.2 on 2023-05-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0013_comparison_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NEW', max_length=15),
        ),
    ]
