# Generated by Django 4.1.2 on 2023-05-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0014_comparison_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='elapsed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
