# Generated by Django 4.1.9 on 2023-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0014_remove_dashboard_dashboard_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
