# Generated by Django 4.1.2 on 2023-05-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0015_comparison_elapsed_time_comparison_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='base_tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comparisons.basetool'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='error_msg',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='linkage_method',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('COMPLETE', 'Complete'), ('UPGMA', 'UPGMA'), ('NJ', 'Neighbor Joining')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='comparison',
            name='microreact_project',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='newick',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
