# Generated by Django 4.1.2 on 2023-05-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0017_comparison_folder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='folder_path',
        ),
    ]
