# Generated by Django 4.1.2 on 2023-05-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0018_remove_comparison_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='folder_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
