# Generated by Django 4.1.2 on 2023-05-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0020_comparison_data_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='data_fields',
        ),
    ]
