# Generated by Django 4.1.2 on 2023-05-11 09:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0022_comparison_data_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='data_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None),
        ),
    ]
