# Generated by Django 4.1.2 on 2023-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0023_alter_comparison_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='comparison',
            field=models.ManyToManyField(to='comparisons.comparison'),
        ),
    ]
