# Generated by Django 4.1.2 on 2023-05-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0024_cluster_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialoutbreak',
            name='comparison',
            field=models.ManyToManyField(to='comparisons.comparison'),
        ),
    ]
