# Generated by Django 4.1.2 on 2023-05-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0026_remove_cluster_merged_into'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='subcluster',
        ),
    ]
