# Generated by Django 4.1.2 on 2023-05-12 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comparisons', '0027_remove_cluster_subcluster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SequenceSet',
            new_name='SequenceGroup',
        ),
    ]
