# Generated by Django 4.1.2 on 2023-05-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0028_rename_sequenceset_sequencegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='sequence_set',
            new_name='sequence_group',
        ),
        migrations.RenameField(
            model_name='comparison',
            old_name='sequence_set',
            new_name='sequence_group',
        ),
    ]
