# Generated by Django 4.1.2 on 2023-05-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0030_remove_cluster_sequence_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='comparison',
        ),
    ]
