# Generated by Django 4.1.2 on 2023-05-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0031_remove_cluster_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencegroup',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comparisons.cluster'),
        ),
    ]
