# Generated by Django 4.1.2 on 2023-05-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0035_cluster_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='species',
        ),
    ]
