# Generated by Django 4.1.2 on 2023-05-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0036_remove_cluster_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comparisons.species'),
        ),
    ]
