# Generated by Django 4.1.2 on 2023-06-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0040_distancematrix_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenceset',
            name='sequences',
        ),
    ]
