# Generated by Django 4.1.2 on 2023-06-15 09:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0041_remove_sequenceset_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceset',
            name='sequences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
    ]
