# Generated by Django 4.1.2 on 2023-06-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0042_sequenceset_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='base_tool',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='error_msg',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='folder_path',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='linkage_method',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='newick',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='params',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='sequence_set',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='status',
        ),
    ]
