# Generated by Django 4.1.2 on 2023-06-15 09:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comparisons', '0043_remove_comparison_base_tool_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='cluster',
            name='sequences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='comparison',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparison',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparison',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='sequences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='comparison',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comparisons.species'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comparisons.species'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SequenceSet',
        ),
    ]
