# Generated by Django 4.1.2 on 2023-06-15 10:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0044_alter_cluster_options_cluster_sequences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='data_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None),
        ),
    ]
