# Generated by Django 4.1.2 on 2023-06-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0045_alter_comparison_data_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistanceMatrix',
        ),
    ]
