# Generated by Django 4.1.2 on 2023-06-15 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0046_delete_distancematrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distances', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None), size=None)),
            ],
        ),
    ]
