# Generated by Django 4.1.2 on 2023-06-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0047_distancematrix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancematrix',
            options={'verbose_name_plural': 'distance Matrices'},
        ),
        migrations.AddField(
            model_name='comparison',
            name='distance_matrix',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comparisons.distancematrix'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='tree_average',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_average', to='comparisons.tree'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='tree_complete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_complete', to='comparisons.tree'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='tree_single',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_single', to='comparisons.tree'),
        ),
    ]
