# Generated by Django 4.1.2 on 2023-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0048_alter_distancematrix_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='newick',
            field=models.TextField(default='()'),
        ),
    ]
