# Generated by Django 4.1.2 on 2023-06-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0049_tree_newick'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DM_REQ', 'Distance matrix requested'), ('DM_OK', 'Distance matrix OK'), ('DM_ERR', 'Error receiving distance matrix')], default='NEW', max_length=15),
        ),
    ]
