# Generated by Django 4.1.2 on 2023-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0050_comparison_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='distance_matrix',
        ),
        migrations.AddField(
            model_name='comparison',
            name='distances',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
