# Generated by Django 4.1.2 on 2023-06-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0054_alter_comparison_dm_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancematrix',
            options={'verbose_name_plural': 'distance matrices'},
        ),
    ]
