# Generated by Django 4.1.2 on 2023-06-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0055_alter_distancematrix_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='comparison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comparisons.comparison'),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('COMPLETE', 'Complete'), ('AVERAGE', 'Average')], default='SINGLE', max_length=10),
        ),
    ]
