# Generated by Django 4.1.2 on 2023-06-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0056_tree_comparison_tree_tree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='comparison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comparisons.comparison'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(choices=[('single', 'Single'), ('complete', 'Complete'), ('average', 'Average')], default='single', max_length=10),
        ),
    ]
