# Generated by Django 4.1.2 on 2023-07-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0057_alter_tree_comparison_alter_tree_tree_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseTool',
            new_name='ComparisonTool',
        ),
    ]
