# Generated by Django 4.1.2 on 2023-07-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0058_rename_basetool_comparisontool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistanceMatrix',
        ),
    ]
