# Generated by Django 4.1.2 on 2023-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0059_delete_distancematrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialoutbreak',
            name='outbreak_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
