# Generated by Django 4.1.2 on 2023-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0060_potentialoutbreak_outbreak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisontool',
            name='status',
            field=models.CharField(choices=[('testing', 'Testing'), ('accredited', 'Accredited'), ('unavailable', 'Unavaliable')], default='testing', max_length=11),
        ),
    ]
