# Generated by Django 4.1.2 on 2023-07-10 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0061_comparisontool_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisontool',
            name='execution_model',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('direct', 'Direct'), ('mongodb_queue', 'MongoDB Queue')], max_length=13), default=['direct'], size=None),
        ),
        migrations.AlterField(
            model_name='comparisontool',
            name='status',
            field=models.CharField(choices=[('testing', 'Testing'), ('accredited', 'Accredited'), ('unavailable', 'Unavailable')], default='testing', max_length=11),
        ),
    ]
