# Generated by Django 4.1.2 on 2023-07-10 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0062_comparisontool_execution_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisontool',
            name='execution_model',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('direct', 'Direct'), ('mongodb_queue', 'MongoDB Queue')], max_length=13), default=['d', 'i', 'r', 'e', 'c', 't'], size=None),
        ),
    ]
