# Generated by Django 4.1.2 on 2023-07-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0064_alter_comparisontool_execution_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='tool',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='comparisons.comparisontool'),
            preserve_default=False,
        ),
    ]
