# Generated by Django 4.1.2 on 2023-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0065_comparison_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={},
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('species', 'st', 'cluster_number'), name='species_st_clusternumber_unique'),
        ),
    ]
