# Generated by Django 4.0.7 on 2022-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rtjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtjob',
            name='allele_profile_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='newick',
            field=models.TextField(blank=True, null=True),
        ),
    ]
