# Generated by Django 4.0.7 on 2022-09-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rtjob_allele_profile_path_rtjob_newick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtjob',
            old_name='allele_profile_path',
            new_name='data_path',
        ),
    ]
