# Generated by Django 4.0.7 on 2022-09-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_allele_profile_path_rtjob_data_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtjob',
            old_name='data_path',
            new_name='path',
        ),
    ]
