# Generated by Django 4.0.7 on 2022-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_data_path_rtjob_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtjob',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
