# Generated by Django 4.0.7 on 2022-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rtjob_ended_at_rtjob_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='status',
            field=models.CharField(choices=[('INITIALIZED', 'Initialized'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('INVALID', 'Invalid')], default='INITIALIZED', max_length=12),
        ),
    ]
