# Generated by Django 4.0.7 on 2022-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_rtjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('INVALID', 'Invalid')], default='NEW', max_length=12),
        ),
    ]
