# Generated by Django 4.0.7 on 2022-09-07 11:41

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_rtjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtjob',
            name='metadata_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=main.models.get_default_metadata_fields, size=None),
        ),
    ]
