# Generated by Django 4.0.7 on 2022-09-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rtjob_metadata_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtjob',
            old_name='ended_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='rtjob',
            old_name='started_at',
            new_name='start_time',
        ),
    ]
