# Generated by Django 4.0.7 on 2022-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rtjob_cluster_composition_rtjob_elapsed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtjob',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
