# Generated by Django 4.0.7 on 2022-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_rtjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtjob',
            name='path',
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('SUCCESS', 'ReporTree successful'), ('ALL_DONE', 'All done'), ('OS_ERROR', 'OS error'), ('RT_ERROR', 'ReporTree error'), ('OBSOLETE', 'Obsolete')], default='NEW', max_length=15),
        ),
    ]
