# Generated by Django 4.0.7 on 2022-09-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_rtjob_path_alter_rtjob_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtjob',
            old_name='cluster_composition',
            new_name='clusters',
        ),
    ]
