# Generated by Django 4.0.7 on 2022-10-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_dataset_options_alter_rtjob_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(max_length=30)),
                ('cluster_no', models.IntegerField()),
                ('allelic_distance', models.IntegerField()),
                ('samples', models.JSONField()),
                ('rt_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rtjob')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('rt_job', 'partition', 'cluster_no'), name='clusters_unique_constraint'),
        ),
    ]
