# Generated by Django 4.1.2 on 2022-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_cluster_cluster_clusters_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_name',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
    ]
