# Generated by Django 4.1.2 on 2022-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_cluster_cluster_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cluster',
            name='clusters_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('rt_job', 'partition', 'cluster_name'), name='clusters_unique_constraint'),
        ),
    ]
