# Generated by Django 4.1.2 on 2022-10-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_rtjob_clusters'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cluster',
            name='clusters_unique_constraint',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='allelic_distance',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='partition',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='rt_job',
        ),
    ]
