# Generated by Django 4.1.2 on 2022-10-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_cluster_clusters_unique_constraint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rt_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rtjob')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='partition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.partition'),
            preserve_default=False,
        ),
    ]
