# Generated by Django 4.1.2 on 2022-10-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_cluster_clusters_unique_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cluster',
            name='clusters_unique_constraint',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='cluster_name',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('partition', 'name'), name='clusters_unique_constraint'),
        ),
    ]
