# Generated by Django 4.1.2 on 2022-10-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_cluster_clusters_unique_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtjob',
            name='partitions',
        ),
    ]
