# Generated by Django 4.1.2 on 2022-11-23 14:24

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_rtjob_partitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtjob',
            name='analysis',
            field=models.CharField(default='grapetree', max_length=25),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='columns_summary_report',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=main.models.get_default_metadata_fields, size=None),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='count_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=main.models.get_default_metadata_fields, size=None),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='frequency_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=main.models.get_default_metadata_fields, size=None),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='matrix_4_grapetree',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='metadata2report',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=main.models.get_default_metadata_fields, size=None),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='mx_transpose',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtjob',
            name='threshold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), default=[4, 7, 14], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='species',
            field=models.CharField(choices=[('campy', 'Campylobacter jejuni'), ('coli', 'Escherichia coli'), ('listeria', 'Listeria monocytogenes'), ('salmonella', 'Salmonella enterica'), ('none', 'Not species-specific')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('SUCCESS', 'ReporTree successful'), ('ALL_DONE', 'All done'), ('OS_ERROR', 'OS error'), ('RT_ERROR', 'ReporTree error'), ('OBSOLETE', 'Obsolete'), ('SAMPLE_ERROR', 'Sample error'), ('UNKNOWN', 'Unknown error')], default='NEW', max_length=15),
        ),
    ]
