# Generated by Django 4.1.2 on 2022-11-23 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rtjob_analysis_rtjob_columns_summary_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='threshold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
