# Generated by Django 4.1.2 on 2022-12-10 13:42

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_rtjob_count_matrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='count_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=main.models.get_default_matrix_fields, size=None, validators=[main.models.validate_two_elements]),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='frequency_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=main.models.get_default_matrix_fields, size=None, validators=[main.models.validate_two_elements]),
        ),
    ]
