# Generated by Django 4.1.2 on 2023-01-02 12:20

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_dataset_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='count_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None, validators=[main.models.validate_two_elements]),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='frequency_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None, validators=[main.models.validate_two_elements]),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='matrix_4_grapetree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='metadata2report',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='mx_transpose',
            field=models.BooleanField(default=False),
        ),
    ]
