# Generated by Django 4.1.2 on 2023-01-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_rtjob_count_matrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='analysis',
            field=models.CharField(default='HC', max_length=25),
        ),
    ]
