# Generated by Django 4.1.2 on 2023-01-09 14:39

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_rtjob_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='threshold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=main.models.get_default_thresholds, size=None),
        ),
    ]
