# Generated by Django 4.1.2 on 2023-01-10 10:48

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_rtjob_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='count_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None, validators=[main.models.validate_two_elements]),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='frequency_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None, validators=[main.models.validate_two_elements]),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='metadata2report',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None),
        ),
    ]
