# Generated by Django 4.1.2 on 2023-01-11 08:00

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_rtjob_count_matrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='threshold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=main.models.get_default_thresholds, size=None),
        ),
    ]
