# Generated by Django 4.1.2 on 2023-01-17 09:54

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_rtjob_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtjob',
            name='analysis',
            field=models.CharField(default='HC', help_text="Must be 'HC', 'grapetree', or 'treecluster'.", max_length=25),
        ),
        migrations.AlterField(
            model_name='rtjob',
            name='threshold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=main.models.get_default_thresholds, help_text='See https://github.com/insapathogenomics/ReporTree and look for --threshold or --HC-threshold, depending on analysis argument (treecluster analysis is not supported).', size=None),
        ),
    ]
