# Generated by Django 4.1.2 on 2023-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_rtjob_analysis_alter_rtjob_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtjob',
            name='log',
        ),
        migrations.RemoveField(
            model_name='rtjob',
            name='newick',
        ),
        migrations.AddField(
            model_name='rtjob',
            name='newicks',
            field=models.JSONField(default=dict),
        ),
    ]
